version: '3'
volumes: {home:, db:, venv:}
networks: {default:}
services:
  db:
    environment: ["POSTGRES_USER=django", "POSTGRES_PASSWORD=django"]
    image: "mdillon/postgis:9.6-alpine"
    volumes: ["db:/var/lib/postgresql/data"]
  backend: &backend
    image: "ionata/django-backend"
    command: "poetry run /var/www/src/manage.py runserver_plus 0.0.0.0:8000 --nopin"
    links: ["db"]
    env_file: ["./.env"]
    stdin_open: true
    tty: true
    volumes:
      - "home:/root"
      - "venv:/var/www/.venv"
      - ".:/var/www"
  web:
    image: "nginx:mainline-alpine"
    links: ["backend"]
    ports: ["8000:80"]
    volumes:
      - "./conf/docker/nginx.conf:/etc/nginx/nginx.conf"
